name: Performance Tests

on:
  workflow_dispatch:
  pull_request:
    branches: [ cpp17 ]

env:
  BUILD_TYPE: Debug

jobs:
  performance_test:
    runs-on: ${{ github.repository_owner == 'intel' && 'intel-' || '' }}ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Install compiler
        run: sudo apt update && sudo apt-get install -y clang-14

      - name: Configure CMake
        env:
          CC: "/usr/lib/llvm-14/bin/clang"
          CXX: "/usr/lib/llvm-14/bin/clang++"
          CXX_STANDARD: 20
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        id: build_step
        shell: bash
        run: |
          cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} -t compilation_benchmark | tee ${{github.workspace}}/build/compilation_output.log
          echo "compile_benchmark_time="`grep "Clang front-end timer" ${{github.workspace}}/build/compilation_output.log | awk '{print $1}'` >> $GITHUB_OUTPUT

      - name: 'Upload Compilation Trace'
        uses: actions/upload-artifact@v3
        with:
          name: compilation_trace.json
          path: ${{github.workspace}}/build/benchmark/CMakeFiles/compilation_benchmark.dir/big_nexus.cpp.json

